#!/bin/bash
sudo apt install arandr -y;
sudo apt install feh -y;
sudo apt install fonts-font-awesome -y;

CURRENT_DIR=$(pwd)

# dmenu-extensions
#sudo apt-get install suckless-tools xfonts-terminus
#git clone git@github.com:MarkHedleyJones/dmenu-extended.git
#cd dmenu-extended
#sudo python setup.py install
#sudo bash systemd-install.sh
#cd ..

# fonte do sistema
cd /tmp
# wget https://github.com/supermarin/YosemiteSanFranciscoFont/archive/master.zip
# unzip master.zip
cd YosemiteSanFranciscoFont-master

if [ ! -e ~/.fonts ] 
then
	mkdir ~/.fonts
fi

mv *.ttf ~/.fonts/

sudo apt-get install lxappearance

: '
CURENT_DIR=$(pwd)


# font awesome

if [ ! -e ~/.fonts/fontawesome-webfont.ttf ]
then
	cd /tmp
	git clone git@github.com:creationix/font-awesome.git
	cd font-awesome
	cd font
	
	if [ ! -e ~/.fonts ] 
	then
		mkdir ~/.fonts
	fi
	
	mv fontawesome-webfont.ttf ~/.fonts/
	cd ~/.fonts/
	cd "${CURRENT_DIR}"
fi'
