#!/bin/bash
sudo apt install arandr -y;
sudo apt install feh -y;
sudo apt install fonts-font-awesome -y;

# dmenu-extensions
#sudo apt-get install suckless-tools xfonts-terminus
#cd /tmp
#git clone git@github.com:MarkHedleyJones/dmenu-extended.git
#cd dmenu-extended
#sudo python setup.py install
#sudo bash systemd-install.sh
#cd ..
: '
CURENT_DIR=$(pwd)


# font awesome

if [ ! -e ~/.fonts/fontawesome-webfont.ttf ]
then
	cd /tmp
	git clone git@github.com:creationix/font-awesome.git
	cd font-awesome
	cd font
	
	if [ ! -e ~/.fonts ] 
	then
		mkdir ~/.fonts
	fi
	
	mv fontawesome-webfont.ttf ~/.fonts/
	cd ~/.fonts/
	cd "${CURRENT_DIR}"
fi'
